== Configuring Selenoid
This section describes supported ways of automatic https://github.com/aerokube/selenoid[Selenoid] configuration.

[TIP]
====
To quickly configure and run Selenoid type:

    $ ./cm selenoid start
    
====

Selenoid can be configured in two ways:

* Using https://docker.com/[Docker] containers.
* Using standalone binaries - when Docker is not installed.

Which mode to use is detected automatically by trying to access Docker API. To view the list of available commands:

    $ ./cm selenoid --help
    
To launch command:

    $ ./cm selenoid <command> [args...]

Supported commands are:

.Commands to configure and run Selenoid 
|===
| Command | Meaning

| cleanup | Removes Selenoid traces
| configure | Creates Selenoid configuration file (implies download)
| download | Downloads Selenoid binary or container image
| start | Starts Selenoid process or container (implies download and configure)
| stop | Downloads Selenoid binary or container image
| update | Updates Selenoid and configuration to latest version
|===

To see supported flags for each command append `--help`:

    $ ./cm selenoid start --help

=== Example Commands
* `download` command downloads latest or specified Selenoid release as standalone binary or container image:

    $ ./cm selenoid download [--version 1.2.1] [--force]
+
Does nothing when already downloaded. Use `--force` flag to download again.
* `configure` command in addition to downloading Selenoid also downloads container images or webdriver binaries and generates configuration file:

    $ ./cm selenoid configure [--browsers firefox,opera] [--last-versions 2] [--tmpfs 128]
+    
Use `--browsers` to limit browsers to be configured, `--tmpfs` - to add https://en.wikipedia.org/wiki/Tmpfs[Tmpfs] support, `--last-versions` - to limit how many last browser versions to download. If you wish to download all available versions - specify `--last-versions 0`.

* `start` command configures Selenoid and starts it:

    $ ./cm selenoid start
    
By default Selenoid data is stored in `~/.aerokube/selenoid` but you can specify another directory using `--config-dir` flag.