== Quick Start Guide

To start Selenoid:

. Download the latest release binary from https://github.com/aerokube/cm/releases/latest[GitHub releases] for your platform (linux/darwin/windows).

. Having the binary launch one command:
+
.On Linux and Mac OS
[source,bash]
----
$ ./cm selenoid start --vnc
----
+
.On Windows
[source,powershell]
----
> ./cm.exe selenoid start --vnc
----

[WARNING]
====
If you are working behind proxy you should set environment variables `HTTP_PROXY`, `HTTPS_PROXY` or `NO_PROXY`
described in https://docs.docker.com/engine/admin/systemd/#runtime-directory-and-storage-driver[Docker documentation]:
[source,bash,subs="attributes+"]
$ HTTP_PROXY=http://proxy.example.com:80/ ./cm selenoid start
====


== Configuring Selenoid
This section describes supported ways of automatic https://github.com/aerokube/selenoid[Selenoid] configuration.

[TIP]
====
To quickly configure and run Selenoid with defaults type:

[source,bash]
----
./cm selenoid start
----

====

Selenoid can be configured in two ways:

* Using https://docker.com/[Docker] containers (default)
* Using standalone binaries (when `--use-drivers` is added)

To view the list of available commands:

[source,bash]
----
./cm selenoid --help
----

To launch command:

[source,bash]
----
./cm selenoid <command> [args...]
----

Supported commands are:

.Commands to configure and run Selenoid
|===
| Command | Meaning

| args | Print Selenoid command line arguments
| cleanup | Removes Selenoid traces
| configure | Creates Selenoid configuration file (implies download)
| download | Downloads Selenoid binary or container image
| start | Starts Selenoid process or container (implies download and configure)
| status | Shows actual configuration status (whether Selenoid is downloaded, configured or running)
| stop | Stops Selenoid process or container
| update | Updates Selenoid and configuration to latest version
|===

To see supported flags for each command append `--help`:

[source,bash]
----
./cm selenoid start --help
----

=== Example Commands
* `download` command downloads latest or specified Selenoid release as standalone binary or container image:
+
[source,bash]
----
./cm selenoid download --version 1.2.1 --force
----
+
This command does nothing when already downloaded. Use `--force` flag to download again.


* `configure` command in addition to downloading Selenoid also downloads container images or webdriver binaries and generates configuration file:
+
[source,bash]
----
./cm selenoid configure --browsers firefox:>45.0;opera:53.0;android --last-versions 2 --tmpfs 128
----
+
Use `--browsers` to limit browsers to be configured, `--tmpfs` - to add https://en.wikipedia.org/wiki/Tmpfs[Tmpfs] support, `--last-versions` - to limit how many last browser versions to download. If you wish to download all available versions - specify `--last-versions 0`.


* `start` command configures Selenoid and starts it:
+
[source,bash]
----
./cm selenoid start
----
+
By default Selenoid data is stored in `~/.aerokube/selenoid` but you can specify another
directory using `--config-dir` flag. To download images with VNC server (to see live browser screen) use `--vnc` flag:
+
[source,bash]
----
./cm selenoid start --vnc
----
+
To override Selenoid listen port add `--port` flag:
+
[source,bash]
----
./cm selenoid start --port 4445
----
+
To override Selenoid startup arguments sessions add `--args` flag:
+
[source,bash]
----
./cm selenoid start --args "-limit 10"
----
+
To download images from private registry - log in with `docker login` command and add `--registry` flag:
+
[source,bash]
----
docker login my-registry.example.com # Specify user name and password
./cm selenoid start --registry https://my-registry.example.com
----

=== Downloading Only Some Browser Versions

By default CM downloads browser images corresponding to 2 last versions of Firefox, Chrome and Opera. To download concrete browser versions - use `--browsers` flag as follows:

.Download concrete versions of Firefox and Chrome
[source,bash]
----
./cm selenoid start --browsers 'firefox:51.0;firefox:55.0;chrome:66.0'
----

.Download a range of Firefox versions and 3 last Opera versions
[source,bash]
----
./cm selenoid start --browsers 'firefox:>51.0,<=55.0;opera' --last-versions 3
----

.Download Android image (not downloaded by default because of image size)
[source,bash]
----
./cm selenoid start --browsers 'android:6.0'
----

=== Using Existing Configuration File

In some cases you may want to configure Selenoid to use an existing `browsers.json` configuration file. This is mainly needed to always use the same browser versions instead of downloading latest versions. To achieve this:

. Prepare a desired `browsers.json` configuration file
. Launch `cm` with `--browsers-json` flag:
+
[source,bash]
----
./cm selenoid start --browsers-json /path/to/browsers.json
----
